[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "polly_tts_flask"
dynamic = ["version", "dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}